## Python Practical.

In [1]:
print("This is KP")

This is KP


# How do i store data ?
ans. variables --- Data/Values can be stored in temporary spaces called variables.
each variables has a name and address.

In [7]:
var = "Sam"
var

'Sam'

In [10]:
var = "John"
var

'John'

In [14]:
var = "Boby"
var

'Boby'

In [16]:
var

'Boby'

In [ ]:
Data type : Every variable is associated with data-type 
int:1,2,3. float=1.90 string="KP" bollean=True complex=3-4j

In [19]:
a1 = 45
a1

45

In [20]:
type(a1)

int

In [21]:
a1 = 45.9
type(a1)

float

In [22]:
a1 = True
type(a1)

bool

In [28]:
a1 = true
type(a1)

NameError: name 'true' is not defined

In [29]:
a1 = False
type(a1)

bool

In [31]:
a1 = "KP"
type(a1)

str

In [32]:
a1 = 3+4j
type(a1)

complex

In [34]:
#Operator
#Arithmetic Operators = +,-,*,/,**

In [35]:
a = 10 
b = 20
a,b

(10, 20)

In [41]:
a + b

30

In [38]:
c=a+b
c

30

In [42]:
a - b

-10

In [43]:
a * b

200

In [44]:
b / a

2.0

In [46]:
b ** a

10240000000000

In [ ]:
#relational operators < , > , == , !=.

In [57]:
a = 45
b = 9

In [56]:
a == b

False

In [55]:
a != b

True

In [59]:
a > b

True

In [58]:
a<b

False

In [ ]:
#Logical Operators &-and,|-or

In [60]:
a = True
b = False 

In [61]:
a & a

True

In [62]:
a & b

False

In [64]:
b & a

False

In [65]:
b & b

False

In [66]:
b | a

True

In [67]:
b | b

False

In [ ]:
#Python token - smallest meaningful Components 
#Keyword are specoal reserved words.
True , class,

In [70]:
True = "kp"

SyntaxError: cannot assign to True (<ipython-input-70-ae5f61248d02>, line 1)

In [71]:
#identifires are names used for var,function or objects.
#No start with _ , do digit , 
student = "M"

In [72]:
Studnet = "KP"

In [73]:
student

'M'

In [76]:
Studnet

'KP'

In [ ]:
#literals - i am constant,don't change,
a = 3.14, a = "Hello world"

In [77]:
#String = sewuence of charactor 'k',"kp","'op'"

In [78]:
str1 = 'This is my Phone'
str1

'This is my Phone'

In [81]:
str2 = "This is my new iphone"
str2

'This is my new iphone'

In [83]:
str3 = '''

THis is mu 
fed
de
dede

str3'''
str3

'\n\nTHis is mu \nfed\nde\ndede\n\nstr3'

In [89]:
str = "Kiran Prajapati"
str[0]

'K'

In [90]:
str[-1]

'i'

In [92]:
#last value is not count
str[4:9]

'n Pra'

In [93]:
str[4:4]

''

In [95]:
len(str)

15

In [97]:
str.lower()

'kiran prajapati'

In [100]:
len(str[3:5])

2

In [101]:
str.upper()

'KIRAN PRAJAPATI'

In [102]:
str[4:9].lower()

'n pra'

In [103]:
str

'Kiran Prajapati'

In [104]:
str.replace('a','T')

'KirTn PrTjTpTti'

In [105]:
str.replace('t','a')

'Kiran Prajapaai'

In [107]:
str.replace('K','T')

'Tiran Prajapati'

In [108]:
str_new = "op bolte op bolte op bolte 99 99 99 090 990 99"
str_new

'op bolte op bolte op bolte 99 99 99 090 990 99'

In [112]:
str_new.count('9')

11

In [113]:
str_new.count('99')

5

In [114]:
str_new.count('o')

6

In [115]:
str_new.count('op')

3

In [118]:
s1 = "hello world is awesome"
s1.find('i')


12

In [120]:
s1.find('o')

4

In [129]:
s2 = "My Name is Kiran Prajaipatip"

In [135]:
s2.split('M')

['', 'y Name is Kiran Prajaipati']

In [137]:
s2.split('a')

['My N', 'me is Kir', 'n Pr', 'j', 'ip', 'ti']

In [ ]:
#Data structure - tuple
#tuple are immutable(no change after save).is an ordered collection of elements enclosed within()

In [139]:
t1 = (1,True,3.14,5-9j,"KP")
t1

(1, True, 3.14, (5-9j), 'KP')

In [140]:
type(t1)

tuple

In [142]:
t1[0]

1

In [143]:
t1[-1]

'KP'

In [144]:
type(t1[-1])

str

In [146]:
t1[2:4]

(3.14, (5-9j))

In [147]:
t1[2] = 23

TypeError: 'tuple' object does not support item assignment

In [148]:
len(t1)

5

In [150]:
tuple = t1
tuple


(1, True, 3.14, (5-9j), 'KP')

In [152]:
len(tuple)

5

In [156]:
t1=(1,2,3,4,5)
t2=(2,3,4,5,6)
print(t1,t2)
print(t1+t2)
len(t1+t2)

(1, 2, 3, 4, 5) (2, 3, 4, 5, 6)
(1, 2, 3, 4, 5, 2, 3, 4, 5, 6)


10

In [160]:
t1[2]*2 

6

In [161]:
max(tuple)

TypeError: '>' not supported between instances of 'complex' and 'float'

In [162]:
max(t1)

5

In [163]:
min(t2)

2

In [165]:
#List - mutable (modify) ordered collection of elements enclosed within []

In [168]:
l1 = [tuple]
l1

[(1, True, 3.14, (5-9j), 'KP')]

In [169]:
type(l1)

list

In [170]:
l1 = [1,3.14,6-5j,True,"KP"]
l1

[1, 3.14, (6-5j), True, 'KP']

In [171]:
l1[0]

1

In [172]:
l1[-1]

'KP'

In [173]:
l1[0:3]

[1, 3.14, (6-5j)]

In [174]:
l1[1:3]

[3.14, (6-5j)]

In [175]:
l1[0]= 2
l1

[2, 3.14, (6-5j), True, 'KP']

In [177]:
l1.append(2324)
l1

[2, 3.14, (6-5j), True, 'KP', 2324]

In [181]:
l1.pop(1)
l1

[2, 'KP', 2324]

In [184]:
l1.append("kpokpo")
l1

[2, 'KP', 2324, 'kpokpo', 'kpokpo', 'kpokpo']

In [186]:
l1.pop()
l1

[2, 'KP', 2324, 'kpokpo']

In [187]:
l1.pop()
l1

[2, 'KP', 2324]

In [188]:
l1.pop(1)
l1

[2, 2324]

In [190]:
l1 = [1,2.13,"kp","iop","ago",3.4,3.45]
l1.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

In [192]:
l1.reverse()
l1

[1, 2.13, 'kp', 'iop', 'ago', 3.4, 3.45]

In [193]:
l1.reverse()
l1

[3.45, 3.4, 'ago', 'iop', 'kp', 2.13, 1]

In [195]:
l1.reverse()
l1

[3.45, 3.4, 'ago', 'iop', 'kp', 2.13, 1]

In [2]:
l1.insert(2,"OP Bolte")
l1


NameError: name 'l1' is not defined

In [7]:
l1 = [3.45, 3.4, 'ago', 'iop', 'kp', 2.13, 1]
l1 * 1

[3.45, 3.4, 'ago', 'iop', 'kp', 2.13, 1]

In [8]:
#dictionary is an unordered collecction of key-value pairs enclosed with{}

In [9]:
d1 = {'apple':30 ,'mango':34}
d1

{'apple': 30, 'mango': 34}

In [10]:
type(d1)

dict

In [35]:
d1["charry"]=30
d1["Ornage"]=45
d1["apple"]=12
d2={"Banana": 90,"Guva":34}
d1.update(d2)
d1.pop("Banana")
d1

{'apple': 12, 'mango': 34, 'charry': 30, 'Ornage': 45, 'Guva': 34}

In [41]:
set = (1,2.3,'kp')
set

(1, 2.3, 'kp')

In [44]:
set.add("KP")
set

AttributeError: 'tuple' object has no attribute 'add'

In [45]:
s1={1,2.34,"KP"}
s1

{1, 2.34, 'KP'}

In [49]:
s1.add(False)
s1

{1, 2.34, False, 'KP'}

In [58]:
s1={1,2,34,5,1,2,3}
s2={1,2,3,4,5,6,7,89,0}
s1.union(s2)

{0, 1, 2, 3, 4, 5, 6, 7, 34, 89}

In [61]:
s3={3,4,5,61}
s1.intersection(s2)
s1


{1, 2, 3, 5, 34}

In [63]:
#if else statementa

In [69]:
a=10
b=20
c=30
if (a>b) & (a<b):
    print("op bolte")
else:
    print("army")

army


In [73]:
t1=("a","b",'b')
if 'a' in t1:
    print("op in chat")
else:
    print("nhi he")
    


op in chat


In [77]:
l1 = ['a','b','c']
if l1[1]=='b':
    l1[1]='z'
l1


['a', 'z', 'c']

In [81]:
d1= {'k1':1,'k2':2,'k3':3}
d1
if d1['k3']==3:
    d1['k3']=4
d1

{'k1': 1, 'k2': 2, 'k3': 4}

In [ ]:
#looping statements are used to repeat a task multiple times 

In [91]:
i=1
while i<=10:
    print(i)
    i=i+1
        

1
2
3
4
5
6
7
8
9
10


In [95]:
i=1
n=2
while(i<=10):
    print(n," * ",i,"=",n*i)
    i=i+1


2  *  1 = 2
2  *  2 = 4
2  *  3 = 6
2  *  4 = 8
2  *  5 = 10
2  *  6 = 12
2  *  7 = 14
2  *  8 = 16
2  *  9 = 18
2  *  10 = 20


In [98]:
#whike with list

In [99]:
l1

['a', 'z', 'c']

In [114]:
l1=[1,2,3,4,5]
i=0
while i<len(l1):
    l1[i]=l1[i]+1
    i=i+1
l1

[2, 3, 4, 5, 6]

In [115]:
#for loop

In [120]:
l1 = ['mango','banana',"kelu"]
l2= ['chair','app','momm']
l1
for i in l1:
    for j in l1:
        print(i,j)
    

mango mango
mango banana
mango kelu
banana mango
banana banana
banana kelu
kelu mango
kelu banana
kelu kelu


In [122]:
#whiat is ffunction .you work with task .running,cycling,deposite and withdraw,balance. one when you can cll i
#functioin to deposite nyumbee hrek bnde ke liye 1000 timmes code likhna bekar he s we use unction and it name it . and byy bsk.
#balnce 5000 code likh diji ye or baki kam ho jayega.

In [125]:
def fun():
    print("Hello word")
fun()

Hello word


In [131]:
def odd_even(x):
    if x%2==0:
        print(x,"number is even")
    else:
        print(x,"number is odd")
odd_even(-2)

-2 number is even


In [138]:
g=lambda x: x*x*x
g(3)

27

In [152]:
li=[1,23,34,45,56,67,78,89,90,0]
l=list(filter(lambda x: (x%2==0), li))
l

[34, 56, 78, 90, 0]

In [153]:
#lambda with map

In [170]:
li=[1,2,3,4,5,6,7,8,9,10]
l=list(map(lambda x: x/2,li))
l

[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

In [172]:
from functools import reduce
q=reduce(lambda x,y:x+y,li)
q

55

In [174]:
#objects orianted programming(oop) 
#you are surrounded with Objects  two concept class templates of reeal0weokd wnentity twp Properties Behaviour color.cost
#class is user define data-type Attributes and methods. 


In [185]:
#class make,capital latter with start,definate call,
class Phone:
    
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost    
    def make_call(self):
        print("I am making a call")
    def play_gmae(self):
        print("I am Gamer")
p1=Phone() #instance 
#object define


In [180]:
p1.make_call()

I am making a call


In [182]:
p1.play_gmae()

I am Gamer


In [191]:

p1.set_color("blue")
p1.set_cost(12344)
p1.show_color()

'blue'

In [192]:
p1.show_cost()

12344

In [ ]:
#constructor help of init method 

In [195]:
class Employee:
    
    def __init__(self,name,age,salary,gender):
        self.name = name
        self.age = age
        self.salary = salary
        self.gender = gender
        
    def show_emp_details(self):
        print("Name of EMP",self.name)
        print("se of emp",self.age)
        print("salry",self.salary)
        print("salary of Emp",self.gender)
    
    def set_color(self,color):
        self.color=color

In [196]:
e1=Employee("Kiran",20,5100000,"Male")
e1.show_emp_details()

Name of EMP Kiran
se of emp 20
salry 5100000
salary of Emp Male


In [ ]:
#inherittance 

In [214]:
class Vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    def show_vehicle_details(self):
        print("mileage is",self.mileage)
        print("cost is",self.cost)
        print("I am a Vhical")
v1=Vehicle(300,5000)
v1.show_vehicle_details()
        
        
        
        
        

mileage is 300
cost is 5000
I am a Vhical


In [252]:
class Car(Vehicle):
    
    def __init__(self,mileage,cost,tyers,hp):
        super().__init__(mileage,cost)
        self.tyers = tyers
        self.hp = hp
    
    def show_car_details(self):
        print("number of tyers in car",self.tyers)
        print("horse power of car",self.hp)
        print("I am BMW")
    

In [254]:
cw = Car(600,1000000,8,600)
cw.show_car_details()

number of tyers in car 8
horse power of car 600
I am BMW


In [255]:
cw.show_vehicle_details()

mileage is 600
cost is 1000000
I am a Vhical


In [ ]:
#parent 1 paretn 2 == child 1 it called multiple inheritance

In [259]:
class Parent1:
    def assign_string_one(self,str1):
        self.str1=str1
    def show_string_one(self):
        return self.str1
    

In [271]:
class Parent2:
    def assign_string_two(self,str2):
        self.str2=str2
    def show_string_two(self):
        return self.str2


In [272]:
class Child(Parent1,Parent2):
    def assign_string_three(self,str3):
        self.str3=str3
    def show_string_three(self):
        return self.str3
    

In [273]:
my_child = Child()
my_child.assign_string_one("I am string of parent 1")
my_child.assign_string_two("I am string of parent 2")
my_child.assign_string_three("I am string of Parent Child")


In [279]:
my_child.show_string_one()

'I am string of parent 1'

In [281]:
my_child.show_string_two()

'I am string of parent 2'

In [282]:
my_child.show_string_three()

'I am string of Parent Child'

In [283]:
#next is multi level inheritance parent-child-Grand-child

In [304]:
class Parent:
    def get_name(self,name):
        self.name = name
    def show_name_(slef):
        return self.name
    

In [308]:
class Child(Parent):
    def get_age(self,age):
        self.age = age
    def show_age(self):
        return self.age


In [342]:
class Grand_Child(Child):
    def get_gender(self,gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [319]:
mc = Grand_Child()

In [330]:
mc.get_name("csxs")

In [331]:
mc.get_age(23)

In [347]:
mc.get_gender('male')

In [351]:
mc.show_age()

23

In [11]:
import numpy as np


In [13]:
l1=[1,2,3,4,5]

In [15]:
n1=np.array(l1)
n1

array([1, 2, 3, 4, 5])

In [16]:
type(n1)

numpy.ndarray

In [20]:
l2=[[1,2,3,4],[1,2,34,4]]
l2

[[1, 2, 3, 4], [1, 2, 34, 4]]

In [22]:
n2=np.array(l2)
n2

array([[ 1,  2,  3,  4],
       [ 1,  2, 34,  4]])

In [23]:
type(n2)

numpy.ndarray

In [34]:
import numpy as np
n3 = np.zeros((3,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
type(n3)

numpy.ndarray

In [40]:
n4 = np.full((3,3),(1,2,3))
n4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [45]:
n4 = np.arange(10,100)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [49]:
n5 = np.arange(1,100,2)
n5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [56]:
import numpy as np
n6 = np.random.randint(100,200,10)
n6

array([163, 102, 119, 142, 157, 191, 107, 114, 193, 164])

In [77]:
import numpy as np
n7 = np.array([[1,2,3],[5,6,7]])
n7.shape

(2, 3)

In [78]:
n7

array([[1, 2, 3],
       [5, 6, 7]])

In [87]:
n7.shape

(3, 2)

In [93]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
n3=np.array([70,80,90])

In [94]:
np.vstack((n1,n2,n3))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [97]:
np.hstack((n1,n2,n3))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [99]:
np.column_stack((n1,n2,n3))

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [108]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80])

In [104]:
np.intersect1d(n1,n2)

array([50, 60])

In [105]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [106]:
np.setdiff1d(n2,n1)

array([70, 80])

In [110]:
n1 = np.array([10,30])
n2 = np.array([20,40])
np.sum([n1,n2])

100

In [111]:
np.sum([n1,n2],axis=0)

array([30, 70])

In [112]:
np.sum([n1,n2],axis=1)

array([40, 60])

In [123]:
n1=np.array([1,2,3,4,5])
n1=n1*10
n1

array([10, 20, 30, 40, 50])

In [125]:
n1=n1/2
n1

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [135]:
n8 = np.random.randint(1,100,10)
n8

array([17, 10, 73, 52, 13, 74, 39, 19, 93, 31])

In [136]:
np.median(n8)

35.0

In [137]:
np.std(n1)

3.5355339059327378

In [138]:
np.mean(n8)

42.1

In [142]:
import numpy as np
n1 = np.array([1,2,3,4,5])
np.save('kp',n1)

In [145]:
new1=np.load('kp.npy')
new1

array([1, 2, 3, 4, 5])

In [147]:
#pandas stands for panel data single-dimensionll multi- series onject os one-d labeled array 

In [150]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [152]:
type(s1)

pandas.core.series.Series

In [158]:
s1 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [161]:
n10 = pd.Series({'a':10,'b':20,'c':30,'kp':40})
n10

a     10
b     20
c     30
kp    40
dtype: int64

In [164]:
n10 = pd.Series({'a':10,'b':20,'c':30,'kp':40},index=['a','b','kp','bp','c','d'])
n10

a     10.0
b     20.0
kp    40.0
bp     NaN
c     30.0
d      NaN
dtype: float64

In [165]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [166]:
s1[3]

4

In [168]:
s1[0:4]

a    1
b    2
c    3
d    4
dtype: int64

In [171]:
s1[1:5]

b    2
c    3
d    4
e    5
dtype: int64

In [174]:
s1 + 5
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [176]:
sq=pd.Series([1,2,3,4,5,6,7,8,9,10])
sq


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [179]:
sq + 5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
9    15
dtype: int64

In [181]:
sq * 2
sq

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [182]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [183]:
s2 = pd.Series([1,3,4,5,5])
s2

0    1
1    3
2    4
3    5
4    5
dtype: int64

In [186]:
sq + s2

0     2.0
1     5.0
2     7.0
3     9.0
4    10.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

In [199]:
s3=pd.DataFrame({'Name':['bob','sam','kp','ap','qa'],'Marks':[23,45,56,12,23]})
s3

Name  Marks
0  bob     23
1  sam     45
2   kp     56
3   ap     12
4   qa     23

In [200]:
iris = pd.read_csv('iris.csv')
iris.head()
iris.describe()
iris.tall()
iris.shape()

FileNotFoundError: [Errno 2] File iris.csv does not exist: 'iris.csv'